$(document).ready(function(){
    $("#libro1R").hide();
    $("#libro2R").hide();
    $("#libro3R").hide();
    $("#libro4R").hide();
    $("#libro5R").hide();
    $("#libro6R").hide();
    $("#libro7R").hide();
    $("#libro8R").hide();
    $("#libro9R").hide();

    //1
    $("#res1D").click(function(){
        $("#libro1D").hide();
        $("#libro1R").show();
    });
    $("#can1").click(function(){
        $("#libro1D").show();
        $("#libro1R").hide();   
    });
    //2
    $("#res2D").click(function(){
        $("#libro2D").hide();
        $("#libro2R").show();
    });
    $("#can2").click(function(){
        $("#libro2D").show();
        $("#libro2R").hide();   
    });
    //3
    $("#res3D").click(function(){
        $("#libro3D").hide();
        $("#libro3R").show();
    });
    $("#can3").click(function(){
        $("#libro3D").show();
        $("#libro3R").hide();   
    });
    //4
    $("#res4D").click(function(){
        $("#libro4D").hide();
        $("#libro4R").show();
    });
    $("#can4").click(function(){
        $("#libro4D").show();
        $("#libro4R").hide();   
    });
    //5
    $("#res5D").click(function(){
        $("#libro5D").hide();
        $("#libro5R").show();
    });
    $("#can5").click(function(){
        $("#libro5D").show();
        $("#libro5R").hide();   
    });
    //6
    $("#res6D").click(function(){
        $("#libro6D").hide();
        $("#libro6R").show();
    });
    $("#can6").click(function(){
        $("#libro6D").show();
        $("#libro6R").hide();   
    });    
    //7
    $("#res7D").click(function(){
        $("#libro7D").hide();
        $("#libro7R").show();
    });
    $("#can7").click(function(){
        $("#libro7D").show();
        $("#libro7R").hide();   
    });
    //8
    $("#res8D").click(function(){
        $("#libro8D").hide();
        $("#libro8R").show();
    });
    $("#can8").click(function(){
        $("#libro8D").show();
        $("#libro8R").hide();   
    });
    //9
    $("#res9D").click(function(){
        $("#libro9D").hide();
        $("#libro9R").show();
    });
    $("#can9").click(function(){
        $("#libro9D").show();
        $("#libro9R").hide();   
    });
});



